version: "3.3"

services:
  db:
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - django_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - nginx_network
  web:
    build: .
    command: bash run.sh
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - nginx_network

  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - redis_network

  celery:
    build: .
    command: celery -A config worker -l INFO
    depends_on:
      - redis
    networks:
      - redis_network


  nginx:
    build: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  django_db_data:
  static_volume:
  media_volume:

