from .check_feedback_claim_view import CheckFeedbackClaimView
from .send_answer2client_feedback_claim import SendAnswerToClientFeedbackClaim
from .add_product_view import AddProductView
from .add_product_img_view import AddProductImageView
from .change_product_info_view import ChangeProductInfoView
from .add_received_product2warehouse import AddReceivedProductToWarehouse
from .change_characteristics_product_view import ChangeCharacteristicsProductView
from .sales_analytics_view import GetSalesAnalyticsView
