from .add_product import AddProductView
from .check_feedback_claim import CheckFeedbackClaimView
from .send_answer_feedback_claim import SendAnswerToClientFeedbackClaim
from .add_product_image import AddProductImageView
from .add_received_product_warehouse import AddReceivedProductToWarehouse
from .change_product_info import ChangeProductInfoView
from .change_characteristics_product import ChangeCharacteristicsProductView
from .sales_analytics import GetSalesAnalyticsView
