# Generated by Django 3.1.3 on 2022-05-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_auto_20210214_2134'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationconfirmationbyemail',
            table='registration_confirmation_by_email',
        ),
    ]
