# Generated by Django 3.1.3 on 2022-02-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0035_auto_20210213_1953'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='imageproduct',
            table='image_product',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
