from .add_comment import AddCommentView
from .add_product_cart import AddProductToCartView
from .cart import CartView
from .contact import ContactsPageView
from .created_order import CreatedOrderView
from .delete_product_in_cart import DeleteProductInCartView
from .feedback import FeedbackView
from .generate_order_pdf import GenerateOrderPdfView
from .history_orders import HistoryOrdersView
from .increase_count_products import IncreaseCountProductsView
from .ordering_payment_delivery import OrderingPaymentDeliveryView
from .ordering_payment_online import OrderingPaymentOnlineView
from .product_list import ProductListView
from .product_details import ProductDetailsView
from .reduce_count_products import ReduceCountProductsView
