# Generated by Django 3.1.3 on 2022-02-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0037_auto_20220226_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество товаров')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store_app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ячейка для хранения одной позиции товара',
                'verbose_name_plural': 'Склад товаров',
                'db_table': 'warehouse',
                'ordering': ['product'],
            },
        ),
        migrations.AlterModelOptions(
            name='productincart',
            options={'ordering': ['cart'], 'verbose_name_plural': 'Количество определенного товара в корзине'},
        ),
        migrations.RenameField(
            model_name='productincart',
            old_name='cart_user',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='productincart',
            old_name='count_product_in_cart',
            new_name='quantity',
        ),
        migrations.AlterModelTable(
            name='productincart',
            table='product_in_cart',
        ),
        migrations.DeleteModel(
            name='WarehouseProducts',
        ),
    ]
