# Generated by Django 3.1.3 on 2022-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0043_auto_20220527_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
