# Generated by Django 3.1.3 on 2022-05-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0044_auto_20220528_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['num_order', 'created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
