version: "3.3"

services:
  db:
    image: postgres:14.3-alpine
    volumes:
      - django_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash run.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - nginx_network

  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A online_store_on_sofa_project worker -l INFO
    depends_on:
      - redis

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - nginx_network

volumes:
  django_db_data:

networks:
  nginx_network:
    driver: bridge